############################################
# Build healthcheck binary in Go
############################################
FROM golang:1.22-bookworm AS build_healthcheck
WORKDIR /app
COPY extra/healthcheck.go extra/healthcheck.go
RUN cd extra && go build -o healthcheck healthcheck.go

############################################
# Build in Node.js
############################################
FROM node:22-bookworm AS build
USER node
WORKDIR /app

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
COPY --chown=node:node .npmrc .npmrc
COPY --chown=node:node package.json package.json
COPY --chown=node:node package-lock.json package-lock.json
RUN npm ci --omit=dev
COPY . .
COPY --chown=node:node --from=build_healthcheck /app/extra/healthcheck /app/extra/healthcheck
RUN mkdir ./data

############################################
# ⭐ Main Image
############################################
FROM node:22-bookworm-slim AS release
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends dumb-init && rm -rf /var/lib/apt/lists/*

LABEL org.opencontainers.image.title="Uptime Pro"
LABEL org.opencontainers.image.source="https://github.com/AxiomOperator/uptime-pro"

ENV UPTIME_PRO_IS_CONTAINER=1

# Copy app files from build layer
COPY --chown=node:node --from=build /app /app

EXPOSE 3001
HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD extra/healthcheck
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node", "server/server.js"]

############################################
# Rootless Image
############################################
FROM release AS rootless
USER node

############################################
# Mark as Nightly
############################################
FROM release AS nightly
RUN npm run mark-as-nightly

FROM nightly AS nightly-rootless
USER node

############################################
# Upload the artifact to Github
############################################
FROM node:22-bookworm-slim AS upload-artifact
WORKDIR /
RUN apt-get update && apt-get install -y --no-install-recommends curl file && rm -rf /var/lib/apt/lists/*

COPY --from=build /app /app

ARG VERSION
ARG GITHUB_TOKEN
ARG TARGETARCH
ARG PLATFORM=debian
ARG FILE=$PLATFORM-$TARGETARCH-$VERSION.tar.gz
ARG DIST=dist.tar.gz

RUN chmod +x /app/extra/upload-github-release-asset.sh

# Dist only
RUN cd /app && tar -zcvf $DIST dist
RUN /app/extra/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=AxiomOperator repo=uptime-pro tag=$VERSION filename=/app/$DIST

